name: hello-world

on:
  push:
    branches:
      - 'main'

jobs:
 build:
    runs-on: ubuntu-latest
    steps:   
     - uses: actions/checkout@v2

     - name: Setup Python version
       uses: actions/setup-python@v2
       with: 
        python-version: 3.8
        
     -
        name: Checkout
        uses: actions/checkout@v3
     -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
     -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
     -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: user/app:latest
