name: hello-world

on: 
  # workflow_dispatch:
  # push:
  #   branches:
  #     - 'master'
  #   tags:
  #     - v1.*.*

jobs:
build:
  runs-on: ubuntu-latest
  steps:   

    - name: Setup Python version
      uses: actions/setup-python@v2
      with: 
      python-version: 3.8
    
    -
      name: Checkout
      uses: actions/checkout@v3  

    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    -
      name : Dump Github context
      env: 
        GITHUB_CONTEXT : ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
      if: runner.os != 'Windows'

    - 
      name: Show Github ref
      run: |
        echo "TAG=${GITHUB_REF:10}" >> @GITHUB_ENV
        echo "$GITHUB_REF"
      if: runner.os != 'Windows'

    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # - name: Extract Git Tag
    #   run: echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
  
    
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello_world:${{ env.GIT_TAG }}