# .github/workflows/version.yml
name: Git Version

on:
  push:
    tag:
      - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
      
      - name: Set Git identity
        run: |
          git config --global user.name "Ritik232"
          git config --global user.email "RMittal@calance.com"

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          custom_tag: ${{ github.ref}}
      
      - name: Check if tag was created
        id: check_tag_created
        run: |
          if [ "$(git tag -l ${{ steps.tag_version.outputs.new_tag }})" == "${{ steps.tag_version.outputs.new_tag }}" ]; then echo "::set-output name=tag_created::true"; else echo "::set-output name=tag_created::false"; fi

      - name: Create a GitHub release
        if: steps.check_tag_created.outputs.tag_created == 'true'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      
      - name: Stop workflow if tag was not created
        if: steps.check_tag_created.outputs.tag_created != 'true'
        run: exit 1

      # - name: Read version number 
      #   id: read-version
      #   run: |
      #     cat VERSION
      #     echo "::set-output name=current_version::$(cat VERSION)"

      # - name: Increment version number
      #   id: increment-version
      #   if: success()
      #   run: |
      #     echo "::set-output name=next_version::${{format('{0}.{1}', ${{steps.read-version.outputs.current_version}}, "1")}}"

      # - name: creating tags
      #   if: success()
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      #   run: | 
      #       git tag -a v${{ steps.increment-version.outputs.next_version }} -m "Version ${{ steps.increment-version.outputs.next_version }}"
      #       git push --tags

      # - name: creating tags
      #   if: success()
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      #   run: | 
      #       git tag -a v${{ github.run_number }} -m "Version ${{ github.run_number }}"
      #       git push --tags
      
      # - name: Use the version
      #   run: |
      #     echo ${{ steps.version.outputs.version }}
      #     echo ${{ steps.version.outputs }}

      # - name: Use the previous version
      #   run: |
      #     echo ${{ steps.version.outputs.previous-version }}

      # - name: Dump GitHub context
      #   id: github_context_step
      #   run: |
      #     echo '${{ toJSON(github) }}'

                # current_version=$(cat VERSION)
          # echo ${{ current_version }}
          # next_version=$((current_version + 1))
          # echo $next_version > VERSION