# .github/workflows/version.yml
name: Git Version

on:
  push:
    tag:
      - v*.*.*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1


      - name: creating tags
        if: success()
        run: | 
            git tag -a v${{ github.run_number }} -m "Version ${{ github.run_number }}"
            git push --tags
      
      # - name: Use the version
      #   run: |
      #     echo ${{ steps.version.outputs.version }}
      #     echo ${{ steps.version.outputs }}

      # - name: Use the previous version
      #   run: |
      #     echo ${{ steps.version.outputs.previous-version }}

      # - name: Dump GitHub context
      #   id: github_context_step
      #   run: |
      #     echo '${{ toJSON(github) }}'